---
title: "Course Materials"
toc: false
date: ""
sidebar: false
format:
  html:
    number-sections: false
execute:
  freeze: false
---

:::{.contents-table .column-body-outset}

|Topic                                  |Author                                 |Links|
|---------------------------------------|---------------------------------------|-----|
|[**WEEK 1**]{.highlight style="display:block;"}                                |||
|[**12-Jun-2023 (Mon)**]{.highlight}    |                                       ||
|Introduction to RaukR                  |Marcin Kierczak & Sebastian DiLorenzo  ||
|Functions and scripts                  |Sebastian DiLorenzo                    |[Slides](slides/scripting/index.html), [Lab](labs/scripting/index.html)|
|Best Coding Practices in R             |Marcin Kierczak                        |[Slides](slides/coding/index.html), [Lab](labs/coding/index.html)|
|Documentation & Publishing with Quarto |Roy Francis                            |[Slides](slides/publishing/index.html), [Lab](labs/publishing/index.html)|
|Debugging, Profiling and Optimisation  |Marcin Kierczak                        |[Slides](slides/debugging/index.html), [Lab](labs/debugging/index.html)|
|[**13-Jun-2023 (Tue)**]{.highlight}    |                                       ||
|Vectorization                          |Sebastian DiLorenzo & Marcin Kierczak  |[Slides](slides/vectorization/index.html), [Lab](labs/vectorization/index.html)|
|Parallelization                        |Sebastian DiLorenzo & Marcin Kierczak  |[Slides](slides/parallelization/index.html), [Lab](labs/parallelization/index.html)|
|Object-oriented programming            |Marcin Kierczak                        |[Slides](slides/oop/index.html), [Lab](labs/oop/index.html)|
|Introduction to Quarto                 |Chris Dervieux, Posit                  |[Slides](https://cderv.github.io/raukr-2023-quarto)|
|Tables with **gt** package             |Richard Iannone, Posit|[Repo](https://github.com/rich-iannone/presentations/tree/main/2023-06-13-Raukr_gt), [Slides](slides/gt.pdf)|
|[**14-Jun-2023 (Wed)**]{.highlight}    |                                       ||
|Tidyverse                              |Marcin Kierczak                        |[Slides](slides/tidyverse/index.html), [Lab](labs/tidyverse/index.html)|
|git with R                             |Sebastian DiLorenzo                    |[Slides](slides/git/index.html), [Lab](labs/git/index.html)|
|reticulate: Combining R with Python    |Nina Norgren                           |[Slides](slides/reticulate/index.html), [Lab](labs/reticulate/index.html)|
|[**15-Jun-2023 (Thu)**]{.highlight}    |                                       ||
|Plotting with ggplot2                  |Roy Francis & Lokesh Manoharan         |[Slides](slides/ggplot/index.html), [Lab](labs/ggplot/index.html)|
|How to repeat yourself with Purrr      |Jenny Bryan, Posit                     |[Repo](https://github.com/jennybc/2023_raukr-purrr-pkg-dev)|
|[**16-Jun-2023 (Fri)**]{.highlight}    |                                       ||
|R Packages                             |Jenny Bryan, Posit                    ||
|Web apps with Shiny                    |Roy Francis & Lokesh Manoharan         |[Slides](slides/shiny/index.html), [Lab](labs/shiny/index.html)|
|[**WEEK 2**]{.highlight style="display:block;"}                                |||
|[**19-Jun-2023 (Mon)**]{.highlight}    |                                       ||
|Statistics and machine learning in R   |Nikolay Oskolkov                       |[Slides](slides/ml/index.html), [Lab](labs/ml/index.html)|
|Tidymodels                             |Max Kuhn, Posit                        |[Slides](slides/tidymodels/index.html)

:::
